# Elastic Search Variables
elasticsearch_host: localhost
systemd_src: elastic-timeout.conf

# Kibana Variables
kibana_host: localhost

# Logstash Variables
logstash_conf: logstash.conf

# Nagios Variables
nagios_user: admin
nagios_password: password

# LAMP Variables
domain: qjblaler-tip
owner: qblaler-tip
group: qblaler-tip
index_html: index.html
ubuntu_src: qjblaler-tip-ubuntu.conf
